-- 코드를 입력하세요

SELECT CATEGORY
     , COUNT(*) AS PRODUCTS
  FROM (
      SELECT SUBSTR(product_code,0,2) AS CATEGORY
      FROM PRODUCT
     WHERE 1=1
  )
WHERE 1=1
GROUP BY CATEGORY
ORDER BY CATEGORY