-- -- 코드를 입력하세요
SELECT A.CATEGORY
     , SUM(B.SALES)
  FROM BOOK A
     , BOOK_SALES B
 WHERE 1=1 
   AND A.BOOK_ID = B.BOOK_ID
   AND B.SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
 GROUP BY A.CATEGORY
 ORDER BY A.CATEGORY

 
 -- SELECT SUM(SALES) FROM BOOK_SALES WHERE BOOK_ID = '1'
 --  AND SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
 