-- 코드를 입력하세요
SELECT A.BOOK_ID
     , B.AUTHOR_NAME
     , TO_CHAR(A.PUBLISHED_DATE, 'YYYY-MM-DD')
  FROM BOOK A
     , AUTHOR B
 WHERE 1=1
   AND A.CATEGORY = '경제'
   AND A.AUTHOR_ID = B.AUTHOR_ID
 ORDER BY A.PUBLISHED_DATE